name: Build

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: rust_toolchain
        with:
          toolchain: stable
          override: true
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ steps.rust_toolchain.outputs.rustc_hash }}
      - name: Run tests
        run: cargo test --all
      - name: Run example scripts
        run: cargo run --release --bin rune -- --recursive --test --experimental -O macros=true scripts
