name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --manifest-path=tools/builder/Cargo.toml
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: target/upload/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}